/* Write your PL/SQL query statement below */
SELECT TO_CHAR(A.SELL_DATE,'YYYY-MM-DD') as SELL_DATE
     , COUNT(A.PRODUCT) AS NUM_SOLD
     , LISTAGG(A.PRODUCT, ',') WITHIN GROUP(ORDER BY A.PRODUCT) PRODUCTS
FROM 
    (  SELECT DISTINCT 
              SELL_DATE
            , PRODUCT 
        FROM  ACTIVITIES 
    ) A
GROUP BY A.SELL_DATE
ORDER BY A.SELL_DATE